### ISSUE TITLE
Creating the Service Backend of the Plugin

### ISSUE THREAD

**Issue by Monviech** [Monviech/os-caddy-plugin#2]
Service Backend + Middelware

- [x] Create a configd action script that starts Caddy with the desired environment variables
- [x] Use OPNsense's template system to generate the appropriate configuration files for Caddy in the /usr/local/etc/caddy/ directory. (Caddyfile)
- [x] Writing the Python scripts for the action.d conf, caddy_control.py
- [x] Writing the actions_caddy.conf
- [x] Create the ServiceController.php that links the actions_caddy.conf to the configd service and to the API
- [x] configctl caddy start/stop/restart
- [x] /usr/local/etc/rc.d/caddy - Creating Service File for FreeBSD init system for caddy
- [x] Create a storage path in the Caddyfile to /usr/local/etc/caddy/ - to store all files, certificates, states etc...
- [x] Set log path to /var/log/caddy/caddy.log

Front End
- [x] Apply button working, triggering the action script and creating the configuration, restarting the service.
- [x] Enable and Disable in General Settings turning Caddy totally off and on.

**Comment by gspannu** [comment]
**I'd be keen to use this....**

Relatively new to Caddy (though have been using OPNsense for over 2 years now).
OPNsense running in Proxmox on a Protectli VP2420.
Loads of other services running as VMs or LXC containers in Proxmox.

I currently use Nginx Proxy Manager (again running as an Alpine container in Proxmox) and manage all Reverse Proxy using thi.... but would like to switch over to Caddy {_as I would rather have Caddy running within OPNsense, all self contained_}

I want to use Cloudflare DNS challenge method for certs (rather than open Port 80).
Also, need to specify just 1 cert (wildcard cert)... e.g. *.mydomain.com
All my VMs will then be accessible by sub1.mydomain.com, sub2.mydomain.com, etc... and that I what I wish to specify in Caddy.

_Look forward to your release..._

**Comment by Monviech** [comment]
@gspannu This is just a small scope personal project and learning effort. I can't implement the more challenging things. I can only offer base functionality, that is the two default ACME challenges of Caddy that need no specific configurations to work. DNS challenge is totally out of scope for me. I'm not even sure if this project will work in the end. :)

**Comment by Monviech** [comment]
Current Service Backend is finished.

**Comment by Monviech** [comment]
@gspannu https://github.com/Monviech/os-caddy-plugin/issues/11
Keep an eye on this, I would need you for testing.

**Comment by gspannu** [comment]
Apologies... I never came back to you on testing and usage.

I was caught up in a few things and only started using this last week. have tested it quite extensively for handles using custom certificates.

**It works exactly as designed 👍** 

**_Many thanks... really appreciated._**
